{% set version = "1.2.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-finetune
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/finetune_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/finetune/finetune_{{ version }}.tar.gz
  sha256: 81ac2a446f16d72e885d6d0fde93c9f4c43a42a18d65697287f3a3cd45c76c1f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dials >=0.1.0
    - r-dplyr >=1.1.1
    - r-ggplot2
    - r-parsnip >=1.1.0
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-tune >=1.2.0
    - r-vctrs
    - r-workflows >=0.2.6
  run:
    - r-base
    - r-cli
    - r-dials >=0.1.0
    - r-dplyr >=1.1.1
    - r-ggplot2
    - r-parsnip >=1.1.0
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-tune >=1.2.0
    - r-vctrs
    - r-workflows >=0.2.6

test:
  requires:
    - r-testthat
    - r-discrim
    - r-kknn
    - r-klar
    - r-lme4
    - r-matrix
    - r-modeldata
    - r-ranger
    - r-rpart
    - r-rsample
    - r-yardstick
  source_files:
    - tests/
  commands:
    - $R -e "library('finetune')"                                                     # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('finetune')\""                                            # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://finetune.tidymodels.org
  dev_url: https://github.com/tidymodels/finetune
  license: MIT
  summary: The ability to tune models is important. 'finetune' enhances the 'tune' package by providing more specialized methods for finding reasonable values of model tuning parameters.  Two racing methods described by Kuhn (2014) <arXiv:1405.6974> are included. An iterative search method using generalized simulated annealing
    (Bohachevsky, Johnson and Stein, 1986) <doi:10.1080/00401706.1986.10488128> is also included.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
